# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download_dataset": "00_core.ipynb",
         "display_large": "00_core.ipynb",
         "rf_feature_importance": "00_core.ipynb",
         "plot_feature_importance": "00_core.ipynb",
         "__rolling_window": "01_evaluation.ipynb",
         "__cvm": "01_evaluation.ipynb",
         "compute_cvm": "01_evaluation.ipynb",
         "__roc_curve_splitted": "01_evaluation.ipynb",
         "compute_ks": "01_evaluation.ipynb",
         "roc_auc_truncated": "01_evaluation.ipynb"}

modules = ["core.py",
           "evaluation.py"]

doc_url = "https://fastai.github.io/hepml/"

git_url = "https://github.com/fastai/hepml/tree/master/"

def custom_doc_links(name): return None
